services:
  - type: web
    name: kosher-gpt-chat
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /health
